<a href="https://colab.research.google.com/github/gautam1218/Data-Science/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct = {
  'name': ["kunnu","Gautam","pankhuri","sagariya"],
  "age" : [21,19,20,22],
  "roll_no" : [44,33,52,71],
}
df = pd.DataFrame(dct)
print(df)

df1 = pd.DataFrame(dct,index=['a','b','c','d'])
display(df1)

       name  age  roll_no
0     kunnu   21       44
1    Gautam   19       33
2  pankhuri   20       52
3  sagariya   22       71

       name  age  roll_no
a     kunnu   21       44
b    Gautam   19       33
c  pankhuri   20       52
d  sagariya   22       71

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.head(10)
df.tail(10)

df.shape
# df.info() #in give information about data of the data(metaData)

# df.describe()

df.iloc[0:5]

# df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:12] #method of filtering data

df2 = df.loc[df["study_hours"]==11]
df2.iloc[4]

study_hours                  11
attendance                   45
sleep_hours                   5
internet_usage                2
assignments_completed         4
previous_score               93
exam_score                100.0
placement_status         Placed
Name: 30, dtype: object

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')

# df.loc[df["assignments_completed"]==8,['assignments_completed']].iloc[1:3]

df.loc[df['assignments_completed']>19]

df["age"]=19
df

# df=df.rename(columns={'assignments_completed':'assign_comleted'}) #rename columns
df.rename(columns={'assignments_completed':'assign_comleted'},inplace=True)
df.head()

df.drop(5,axis=0,inplace=True)
df.head(10)

df.dropna(axis=1,inplace=True)
df.head(10)

,study_hours,attendance,sleep_hours,internet_usage,assign_comleted,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,19
1,4,69,5,3,8,56,100.00,Placed,19
2,11,60,7,6,10,45,100.00,Placed,19
3,8,99,9,8,4,55,90.17,Placed,19
4,5,52,8,6,8,40,78.82,Placed,19
6,10,40,4,11,9,50,98.12,Placed,19
7,3,86,7,3,7,85,100.00,Placed,19
8,7,72,8,5,18,48,96.81,Placed,19
9,11,77,4,9,15,69,100.00,Placed,19
10,11,64,8,8,12,76,100.00,Placed,19

In [ ]:
import pandas as pd

dct = {
    "name":"kunnu",
    "isGF":"kunnu_GF_YES",
    "is_married":"yes",
    "baccha":None
}
df=pd.DataFrame(dct,index=[0])
df.head()
# df.dropna(axis=1,inplace=True)
# df.head()
df.isnull()
df.notnull()

df.fillna("ha ab ho gaya",inplace=True)#replace misiing values
df.head()

# df.unique()#for a series only
# df

    name          isGF is_married         baccha
0  kunnu  kunnu_GF_YES        yes  ha ab ho gaya